-- 1.	Display a list of all data contained within the BOOKS table. 

	SELECT * FROM books;

-- 2.	List the title only of all the books available in inventory, using the BOOKS table. 

	SELECT title FROM books;

-- 3.	List the title and publication date for each book in the BOOKS table. Use the column heading of Publication Date for the Pubdate field. 
	
	SELECT title, pubdate "Publication Date" FROM books;

-- 4.	List the customer number for each customer in the CUSTOMERS table, along with the city and state in which they reside. 

	SELECT customer#, city, state FROM customers;

-- 5.	Create a list containing the name of each publisher, the person usually contacted, and the telephone number of the publisher. Rename the contact column Contact Person in the displayed results. (Hint Use the PUBLISHER table.) 

	SELECT name, contact "Contact Person", phone FROM publisher;

-- 6.	Determine which categories are represented by the current book inventory. List each category only once. 
	
	SELECT DISTINCT category FROM books;

-- 7.	List the customer number from the ORDERS table for each customer who has placed an order with the bookstore. List each customer number only once. 

	SELECT DISTINCT customer# FROM orders;

-- 8.	Create a list of each book title stored in the BOOKS table and the category in which each book belongs. Reverse the sequence of the columns so the category of each book is listed first. 

	SELECT category, title FROM books;

-- 9.	List the first and last name of each author in the AUTHOR table. 

	SELECT fname, lname FROM author;

-- 10.	Create a list of authors that displays the last name followed by the first name for each author. The last names and first names should be separated by a comma and a blank space. 

	SELECT lname ||', '|| fname FROM author;



-- The management of JustLee Books has submitted two requests. The first is for a mailing list of all customers stored in the CUSTOMERS table. The second is for a list of the percentage of profit generated by each book in the BOOKS table. The requests are as follows: 

-- 1.	Create a mailing list from the CUSTOMERS table. The mailing list should display the name, address, city, state, and zip code for each customer. The name of each customer should be listed in order of first name followed by last name. The name of the customer should appear on the first line, the address on the second line, and the city, state, and zip code on the third line. 

	SELECT firstname ||' '|| lastname ||CHR(10)|| address || CHR(10) || city ||', '|| state ||' '|| zip FROM customers;


-- 2.	To determine the percentage of profit for a particular item, subtract the cost for the item from the retail price to obtain the dollar amount of profit, and then divide, the profit by the cost of the item. The solution is then multiplied by 100 to determine the profit percentage for each book. Use a SELECT statement to display the title of each book and its percentage of profit. For the column displaying the percentage markup, use Profit % as the column heading. 

-- Required: Determine the SQL statements needed to perform the two required tasks. Each statement should be tested to ensure its validity. 

	SELECT title, ((retail-cost)/cost)*100 "Profit %" FROM books;